on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: 📂 Lint and format code
        run: |
          npm install --save-dev eslint prettier stylelint stylelint-config-standard
          npm run lint
          npm run format

          if [ $? -eq 0 ]
          then
            echo "Code verification passed"
          else
            echo "Code verification failed"
          fi
      
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}